name: Update changes on commit

on:
  push:
    branches: [ master ]
    paths:
    - 'assets/icons'
    - 'customize/**'
    - 'fonts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: ğŸ–¼ï¸	Update icons
      run:  |
        for dest in customize/* ; do cp -rv assets/icons "$dest"; done
    - name: ğŸ“‡ Update fonts
      run:  |
        for dest in customize/* ; do cp -rva fonts/. "$dest"; done
    - name: ğŸ’¼ Update archives
      run:  |
        cd customize;
        for dest in * ; do find "$dest" -printf "%P\n" | tar -vcf ../themes/"$dest".tar --no-recursion -C "$dest" -T -; done
    - name: ğŸ”¥ Commit changes
      run:  |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git add .
        git commit -m "ğŸ¤– Update files"
        git push
